// app/components/navs/blog.vue
<script lang="ts" setup>
  const query = gql`
    query FetchAllPosts($host: String!) {
      publication(host: $host) {
        posts(first: 0) {
          edges {
            node {
              id
              title
              slug
              subtitle
              coverImage {
                url
              }
              publishedAt
              views
              brief
            }
          }
        }
      }
    }
  `;

  function truncateText(text: string, maxLength: number) {
    if (text && text.length > maxLength) {
      return text.substring(0, maxLength) + "...";
    }
    return text;
  }

  function formatDate(dateString: string) {
    if (!dateString) return "";
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  }

  const variables = { host: "mblessed.hashnode.dev" };

  interface PostNode {
    id: string;
    title: string;
    slug: string;
    subtitle: string;
    coverImage: { url: string };
    publishedAt: string;
    views: number;
    brief: string;
  }

  interface PostsData {
    publication?: {
      posts?: {
        edges: { node: PostNode }[];
      };
    };
  }

  const { data, pending, error } = await useAsyncQuery<PostsData>(
    query,
    variables
  );

  const posts = computed(() => data.value?.publication?.posts?.edges || []);

  // Dropdown state management
  const openPostDropdown = ref<number | null>(null);

  const togglePostDropdown = (id: number) => {
    openPostDropdown.value = openPostDropdown.value === id ? null : id;
  };
</script>

<template>
  <section class="space-y-3 mt-2">
    <section class="space-y-2">
      <h2 class="text-sm tracking-wide flex justify-between items-start">
        <p class="w-2/3">
          <!-- <span class="font-bold">Why I write: </span>
          <span>I write because... </span> -->
        </p>

        <a
          class="underline"
          target="_blank"
          href="https://mblessed.hashnode.dev"
        >
          View All Posts ({{ data?.publication?.posts?.edges.length || 0 }})
        </a>
      </h2>

      <div v-if="pending" class="text-center py-8">
        <p class="text-gray-500 dark:text-gray-400">Loading posts...</p>
      </div>

      <div v-else-if="error" class="text-center py-8">
        <p class="text-red-500">Error loading posts: {{ error.message }}</p>
      </div>

      <div v-else>
        <div
          v-for="(post, id) in posts"
          :key="post.node.id"
          class="border-b border-gray-200 last:border-b-0 dark:border-gray-700"
          @click="togglePostDropdown(id)"
        >
          <div
            class="flex flex-1 justify-between items-start space-x-3 py-2 tracking-wide group cursor-pointer"
          >
            <div class="px-2 flex space-x-4">
              <div
                class="w-16 h-16 rounded-md overflow-hidden bg-gray-200 dark:bg-gray-700 flex-shrink-0"
              >
                <img
                  v-if="post.node.coverImage?.url"
                  :src="post.node.coverImage.url"
                  :alt="post.node.title"
                  class="w-full h-full object-cover"
                />
                <div
                  v-else
                  class="w-full h-full flex items-center justify-center"
                >
                  <svg
                    class="w-6 h-6 text-gray-400"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z"
                    />
                  </svg>
                </div>
              </div>

              <div class="space-y-1 flex-1">
                <h3 class="font-semibold">
                  <p
                    class="group-hover:underline text-gray-600 dark:text-gray-300 group-hover:text-gray-600 dark:group-hover:text-gray-100 hover:text-gray-600 dark:hover:text-gray-100 flex justify-normal items-center space-x-2"
                  >
                    <a
                      :href="`https://mblessed.hashnode.dev/${post.node.slug}`"
                      target="_blank"
                      rel="noopener"
                      class="line-clamp-2"
                      @click.stop
                    >
                      {{ post.node.title }}
                    </a>
                    <span
                      class="transition-transform duration-200 group-hover:rotate-90 flex-shrink-0"
                    >
                      <svg
                        class="inline w-4 h-4 text-gray-400"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        viewBox="0 0 16 16"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M6 4l4 4-4 4"
                        />
                      </svg>
                    </span>
                  </p>
                </h3>
                <p
                  class="block text-sm text-gray-500 dark:text-gray-400 space-x-2 line-clamp-1"
                >
                  <span v-if="post.node.subtitle">{{
                    post.node.subtitle
                  }}</span>
                  <span v-else-if="post.node.brief">{{
                    truncateText(post.node.brief, 80)
                  }}</span>
                </p>
                <p class="block text-xs text-gray-400 dark:text-gray-500">
                  {{ post.node.views }} views
                </p>
              </div>
            </div>
            <div class="text-right flex-shrink-0">
              <p class="block text-xs text-gray-500 dark:text-gray-400">
                {{ formatDate(post.node.publishedAt) }}
              </p>
            </div>
          </div>

          <!-- Dropdown -->
          <Transition name="expand">
            <div
              v-if="openPostDropdown === id"
              class="w-full my-2 bg-gray-100 dark:bg-gray-800 rounded p-3 col-span-2"
            >
              <div class="space-y-3">
                <div v-if="post.node.coverImage?.url" class="w-full">
                  <img
                    :src="post.node.coverImage.url"
                    :alt="post.node.title"
                    class="w-full h-48 object-cover rounded-md"
                  />
                </div>
                <div
                  v-if="post.node.brief"
                  class="text-sm text-gray-600 dark:text-gray-300"
                >
                  {{ post.node.brief }}
                </div>
                <div
                  class="flex justify-between items-center text-xs text-gray-500 dark:text-gray-400"
                >
                  <span
                    >Published: {{ formatDate(post.node.publishedAt) }}</span
                  >
                  <span>{{ post.node.views }} views</span>
                </div>
                <a
                  :href="`https://mblessed.hashnode.dev/${post.node.slug}`"
                  target="_blank"
                  rel="noopener"
                  class="inline-flex items-center text-sm text-blue-600 dark:text-blue-400 hover:underline"
                >
                  Read full article
                  <svg
                    class="w-3 h-3 ml-1"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                    />
                  </svg>
                </a>
              </div>
            </div>
          </Transition>
        </div>
      </div>
    </section>
  </section>
</template>

// src/components/Blog.tsx
import Loader from "@/components/Loader";
import { BLOGS } from "@/data/blog";

import { PostEdge, Publication } from "@/gql/graphql";
import { gql, useQuery } from "@apollo/client";
import { useEffect, useState } from "react";
// import { graphql } from "../gql";

const query: any = gql(`
query FetchAllPosts($host: String!) {
  publication(host: $host) {
    posts(first: 0) {
      edges {
        node {
          id
          title
          slug
          subtitle
          coverImage {
            url
          }
          publishedAt
          views
          brief
        }
      }
    }
  }
}
`);
// const query: any = gql(`
// query FetchPost($slug: String!) {
//   publication(host: $host) {
//     post(slug: $slug) {
//       id
//       title
//       slug
//       subtitle
//       tags {
//         id
//         name
//       }
//       url
//       coverImage {
//         url
//       }
//       readTimeInMinutes
//       publishedAt
//       content {
//         markdown
//         html
//       }
//       views
//     }
//   }
// }
// `);

function truncateText(text: any, maxLength: number) {
  if (text.length > maxLength) {
    return text.substring(0, maxLength) + "...";
  }
  return text;
}

const Blog = () => {
  const blogs = BLOGS;

  const [publications, setPublications] = useState<Publication>();

  const { data, loading } = useQuery(query, {
    variables: { host: "mblessed.hashnode.dev" },
  });

  console.log("The data:", data);
  // console.log("The data:", info);

  useEffect(() => {
    setPublications(data?.publication);
  }, [data]);

  if (loading) return <Loader />;

  return (
    <div className="my-10 md:my-24 mx-4 md:mx-8" id="blog">
      <div className="text-start pt-16 mb-4 text-3xl font-semibold">Blogs</div>
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-5">
        {publications &&
          publications.posts.edges.map((post: PostEdge) => (
            <a
              key={post.node.id}
              href={`https://mblessed.hashnode.dev/${post.node.slug}`}
              target="_blank"
            >
              <div className="text-start flex flex-col justify-between bg-[#18173B] p-4 pt-4 pb-10 rounded-xl mx-auto hover:border hover:border-white h-[260px]">
                <div className="text-base font-semibold mb-4 h-3/6">
                  {truncateText(post.node.title, 50)}
                </div>

                <div className="font-extralight md:font-light mb-10 text-sm h-2/6">
                  {truncateText(post.node.subtitle, 65)}
                </div>

                <div className="text-end text-sm text-[#FFFFFF]/[0.6] h-1/6">
                  {post.node.views} views
                </div>
              </div>
            </a>
          ))}
      </div>
    </div>
  );
};

export default Blog;
