// app/components/navs/projects.vue
<script lang="ts" setup>
  import { PROJECTS } from "~/data/projects";
  import { TOOLS } from "~/data/tools";

  const projects = ref(PROJECTS);
  const tools = ref(TOOLS);
</script>
<template>
  <section class="space-y-3 mt-4">
    <!-- <h2 class="text-sm tracking-wide">
      <span class="font-bold">Why I build: </span>
      <span
        >I build because... For more projects, visit my
        <a
          class="underline"
          target="_blank"
          href="https://github.com/blessemadukoma"
          >GitHub</a
        ></span
      >
    </h2> -->

    <div
      v-for="(project, id) in projects"
      :key="id"
      class="space-y-1 flex items-start space-x-3 py-2 rounded-lg"
    >
      <ui-img :img-url="project.imageURL" />

      <div class="px-2 space-y-2">
        <div class="flex justify-between items-center">
          <h3 class="text-[15px] font-semibold">
            {{ project.title }}
          </h3>

          <p class="text-xs text-gray-500 dark:text-gray-400 space-x-2">
            <span v-if="project.github">
              <a
                :href="project.github"
                target="_blank"
                rel="noopener"
                class="underline hover:text-gray-600 dark:hover:text-gray-300"
                >GitHub</a
              >
            </span>
            <span v-if="project.live">
              <a
                :href="project.live"
                target="_blank"
                rel="noopener"
                class="underline hover:text-gray-600 dark:hover:text-gray-300"
                >Live</a
              >
            </span>
          </p>
        </div>

        <p class="text-sm text-gray-600 dark:text-gray-400">
          {{ project.description }}
        </p>

        <p class="text-xs text-gray-600 dark:text-gray-300">
          <span v-for="(tech, idx) in project.technologies" :key="tech">
            <template
              v-if="
                tools.find((t) => t.name.toLowerCase() === tech.toLowerCase())
              "
            >
              <img
                :src="tools.find((t) => t.name === tech)?.image"
                alt="Tool Image"
                class="inline-block w-4 h-4"
              />
              {{ tech }}
            </template>
            <template v-else>
              {{ tech }}
            </template>
            <span v-if="idx < project.technologies.length - 1">, </span>
          </span>
        </p>
      </div>
    </div>
  </section>
</template>
Projects

// src/components/Projects.tsx
import { LinkIcon } from "@/icons/icons";
import { PROJECTS } from "../data/projects";
import Image from "next/image";

export const Projects = () => {
  const projects = PROJECTS;
  return (
    <div className="py-24">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
        {projects.map((project, id) => (
          <div
            className="flex flex-col w-[340px] mx-auto bg-[#fff]/[0.07] px-5 py-4 rounded-[5px]"
            key={id}
          >
            <div className="mt-4 rounded-[4px] text-lg tracking-wider font-medium mx-auto">
              <Image
                src={project.imageURL}
                className="rounded-[5px] h-[170px]"
                alt={project.alt}
                width={300}
                height={170}
              />
              {/* <img
                src={project.imageURL}
                className="rounded-[5px] max-h-[170px] h-[170px]"
                alt={project.alt}
              /> */}
            </div>
            <div className="text-start mt-6 items-start">
              <h3 className="text-lg font-semibold">{project.title}</h3>
              <p className="py-2 mt-4 text-base font-light text-[#a7a4a5] h-[50px]">
                {project.description}
              </p>
            </div>

            <div className="flex tracking-wide text-sm mb text-start space-x-6 py-6 text-white">
              <a
                href={`${project.github}`}
                target="_blank"
                className="hover:text-[#a7a4a5] hover:border-b"
              >
                <div className="flex items-center">
                  <span className="mr-1">Github</span>
                  <LinkIcon />
                </div>
              </a>

              {project.live && !project.apiDoc ? (
                <a
                  href={`${project.live}`}
                  target="_blank"
                  className={`${
                    project.live
                      ? "visible hover:text-[#a7a4a5] hover:border-b"
                      : "hidden"
                  }`}
                >
                  <div className="flex items-center">
                    <span className="mr-1">Live</span>
                    <LinkIcon />
                  </div>
                </a>
              ) : (
                <a
                  href={`${project.apiDoc}`}
                  className={`${
                    project.apiDoc
                      ? "visible hover:text-[#a7a4a5] hover:border-b"
                      : "hidden"
                  }`}
                >
                  <div className="flex items-center">
                    <span className="mr-1">Doc</span>
                    <LinkIcon />
                  </div>
                </a>
              )}
            </div>

            {/* tools used */}
            <div className="flex flex-wrap mb-4">
              {project.technologies.map((tech, id) => (
                <span
                  className="text-xs flex space-x-8 mb-2 py-1 px-2 rounded-[4px] flex-wrap text-gray-900 mr-3 bg-[#fff]"
                  key={id}
                >
                  {tech}
                </span>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
